[package]
name = "day11"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
num-bigint = "0.4.3"
num-integer = "0.1.45"
num-traits = "0.2.15"
